# -*- coding: utf-8 -*-
"""fast_charger_Map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18EpBXyDrOr25toWMk7fxTGaJdlrbg_PE
"""

import pandas as pd
import folium

dat = pd.read_csv("서울특별시 전동휠체어급속충전기.csv",encoding='cp949')
dat

dat.columns

dat_tmp = dat.loc[ 0:500, ['시설명','위도','경도']]
dat_tmp

m = folium.Map(location = [37.5447, 126.9828], zoom_start=10)
m

dat_tmp.shape

dat_tmp.head()

print( dat_tmp.shape)
dat_tmp = dat_tmp.dropna()
print( dat_tmp.shape)

des = dat_tmp['시설명']
dat_p1 = list( dat_tmp['위도'])
dat_p2 = list( dat_tmp['경도'])

dat_xy = list(zip(dat_p1,dat_p2))
dat_xy[0:3]

dat_tmp.shape

m = folium.Map(location=[37.5447, 126.9828], zoom_start=13)

for name, loc in zip(des, dat_xy):
  folium.Marker(location=loc,
                popup=name,
                tooltip=name,
                icon=folium.Icon(color='blue', icon='info-sign')
                ).add_to(m)
m.save("fast_charger_seoul.html")     
m

